---
blank_issues_enabled: false
contact_links:
  - name: Discuss on Teams
    url: https://teams.microsoft.com/_?tenantId=67481c72-d897-4db4-a7fa-b96d76dfb545#/conversations/General?threadId=19:f26a11412d3d4edebb455e0d32c69d51@thread.tacv2&ctx=channel
    about: Azure Consulting Channel