---
name: ðŸ§³ Build Documentation

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      OrderFile:
        required: true
        type: string
      Title:
        required: false
        type: string
        default: Azure Cloud Framework
      Subtitle:
        required: false
        type: string
        default: DESIGN DOCUMENT
      MetadataFile:
        required: false
        type: string
        default: templates/azure-document.yaml
      Template:
        required: false
        type: string
        default: templates/azure-document.tex
      OutFile:
        required: true
        type: string
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Build Documentation
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "::set-output name=firstword::hello"
      - id: step2
        run: echo "::set-output name=secondword::world"

      - name: Setup pandoc
        env:
          PANDOC_VERSION: "2.18"
        run: |
          wget -qO- "https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-linux-amd64.tar.gz" | sudo tar xzf - --strip-components 1 -C "/usr/local/"

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            ae
            amscls
            amsmath
            babel
            babel-english
            babel-german
            babelbib
            bookmark
            carlisle
            colortbl
            fancyhdr
            fix2col
            geometry
            graphics
            graphics-cfg
            hyperref
            latex
            latex-bin
            latex-fonts
            latexconfig
            ltxmisc
            mfnfss
            mptopdf
            natbib
            oberdiek
            pslatex
            psnfss
            pspicture
            tools
            url
            anysize
            beamer
            booktabs
            breqn
            caption
            cite
            cmap
            crop
            ctable
            eso-pic
            euenc
            euler
            etoolbox
            extsizes
            fancybox
            fancyref
            fancyvrb
            filehook
            float
            fontspec
            fp
            index
            jknapltx
            koma-script
            latexbug
            l3experimental
            l3kernel
            l3packages
            lineno
            listings
            lwarp
            mathspec
            mathtools
            mdwtools
            memoir
            metalogo
            microtype
            ms
            ntgclass
            parskip
            pdfpages
            polyglossia
            powerdot
            psfrag
            rcs
            sansmath
            section
            seminar
            sepnum
            setspace
            subfig
            textcase
            thumbpdf
            translator
            typehtml
            ucharcat
            underscore
            unicode-math
            xcolor
            xkeyval
            xltxtra
            xunicode
            adjustbox
            background
            bidi
            collectbox
            csquotes
            everypage
            filehook
            footmisc
            footnotebackref
            framed
            fvextra
            letltxmacro
            ly1
            mdframed
            mweights
            needspace
            pagecolor
            sourcecodepro
            sourcesanspro
            titling
            ucharcat
            ulem
            unicode-math
            upquote
            xecjk
            xurl
            zref
            awesomebox
            fontawesome5
            tcolorbox
            pgf
            etoolbox
            environ
            trimspaces
            lastpage
            enumitem
            
      - name: Initialization for tlmgr
        run: |
          sudo apt-get update -qq && sudo apt-get install xzdec -y
          tlmgr init-usertree

      - name: Setup fonts and image conversion tool
        run: sudo apt-get update -qq && sudo apt-get install fonts-noto-cjk poppler-utils fonts-crosextra-carlito fonts-crosextra-caladea -y

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install python filters
        run: |
          python -m pip install --upgrade pip
          pip install pandoc-latex-environment

      - name: Clone repository for building
        uses: actions/checkout@v3

      - name: Download the build script
        run: curl -o docs/build-docs.ps1 https://raw.githubusercontent.com/innofactororg/workflows/main/scripts/build-docs.ps1

      - name: Create Template area
        run: mkdir docs/templates

      - name: Download the Cover Image
        run: curl -o docs/templates/cover.png https://raw.githubusercontent.com/innofactororg/workflows/main/templates/cover.png

      - name: Download the Logo
        run: curl -o docs/templates/logo.png https://raw.githubusercontent.com/innofactororg/workflows/main/templates/logo.png

      - name: Download the LaTeX Template
        run: curl -o docs/templates/azure-document.tex https://raw.githubusercontent.com/innofactororg/workflows/main/templates/azure-document.tex

      - name: Download the Pandoc Template
        run: curl -o docs/templates/azure-document.yaml https://raw.githubusercontent.com/innofactororg/workflows/main/templates/azure-document.yaml

      - name: Update the Document Title
        run: yq eval -i '.title = "${{ inputs.Title }}"' docs/templates/azure-document.yaml

      - name: Update the Document Subtitle
        run: yq eval -i '.subtitle = "${{ inputs.Subtitle }}"' docs/templates/azure-document.yaml

      - name: Give script permissions
        run: chmod +x docs/build-docs.ps1

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: false

      - name: Build PDF
        shell: pwsh
        run: |
          $Global:ProgressPreference = 'SilentlyContinue';
          & docs/build-docs.ps1 -OrderFile ${{ inputs.OrderFile }} -MetadataFile ${{ inputs.MetadataFile }} -Template ${{ inputs.Template }} -OutFile ${{ inputs.OutFile }}

      - name: Publish PDF
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.OutFile }}
          if-no-files-found: error
          retention-days: 5
          path: "${{ github.workspace }}/${{ inputs.OutFile }}"